<?php
if (!defined('ABSPATH')) { exit; }

class ALGQ_Offer_Document_Generator {
    public static function init() {
        add_action('wp_ajax_algq_generate_offer_document', array(__CLASS__, 'ajax_generate_document'));
    }

    public static function ajax_generate_document() {
        check_ajax_referer('algq_offer_generator', 'nonce');
        if (!current_user_can('edit_posts')) {
            wp_send_json_error(array('message' => __('Permission denied.', 'algq-offer-generator')), 403);
        }
        $offer_id = isset($_POST['offer_id']) ? absint($_POST['offer_id']) : 0;
        if (!$offer_id || get_post_type($offer_id) !== 'algq_offer') {
            wp_send_json_error(array('message' => __('Invalid offer.', 'algq-offer-generator')), 400);
        }
        $html = self::render_offer_html($offer_id);
        update_post_meta($offer_id, '_algq_offer_document_html', wp_kses_post($html));
        do_action('algq_offer_document_generated', $offer_id, get_current_user_id());
        wp_send_json_success(array('html' => $html));
    }

    public static function render_offer_html($offer_id) {
        $title = get_the_title($offer_id);
        $price = get_post_meta($offer_id, '_algq_offer_price', true);
        $strategy = get_post_meta($offer_id, '_algq_offer_strategy', true);
        $terms = get_post_meta($offer_id, '_algq_offer_terms', true);
        ob_start();
        ?>
        <section class="algq-offer-document">
            <h1><?php echo esc_html($title ?: __('Acquisition Offer', 'algq-offer-generator')); ?></h1>
            <p><strong><?php esc_html_e('Strategy:', 'algq-offer-generator'); ?></strong> <?php echo esc_html($strategy ?: __('Cash / Terms Offer', 'algq-offer-generator')); ?></p>
            <p><strong><?php esc_html_e('Offer Price:', 'algq-offer-generator'); ?></strong> <?php echo esc_html($price ?: __('To be negotiated', 'algq-offer-generator')); ?></p>
            <div><?php echo wpautop(esc_html($terms ?: __('Offer terms will appear here after the builder is completed.', 'algq-offer-generator'))); ?></div>
            <p class="algq-offer-footer"><?php esc_html_e('Generated by Algonquian Real Estate Offer Generator.', 'algq-offer-generator'); ?></p>
        </section>
        <?php
        return ob_get_clean();
    }
}
